os: linux
dist: xenial
language: python
sudo: required
python:
  - "3.7.5"

before_script:
  - apt update
  - apt install npm
  - npm install n -g
  - n lts
  - node -v
  - npm install -g pyright@1.1.86
  - python -V

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

script: 
    - pip install -q  black==20.8b1
    - pip install -q  isort==5.6.4
    - black -v cibo --check
    - black -v demo --check
    - black -v scripts --check
    - isort --check "cibo/" "demo/" "scripts/"
    - pyright
