os: linux
dist: xenial
language: python
python:
  - "3.7.5"

git:
  submodules: false  # Handle git submodules manually

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - nvm install node
  - npm install -g pyright@1.1.166
  - python -V
  - node -v
  - npm -v
  - pyright --version

before_script:
  - pip install -r requirements-dev.txt

script: 
  - black -v src --check
  - black -v demo --check
  - black -v tests --check
  - black -v scripts --check
  - isort --check "src/" "demo/" "tests/" "scripts/"
  - pyright

