[tool.black]
exclude = '''
stubs/.*
'''
line-length = 100
target-version = ['py37']

[tool.isort]
line_length = 100
force_grid_wrap = 0
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -p no:warnings"
testpaths = [
    "./tests",
]
